Others/jobFinder - Django/Finals/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('Jobfinder/', include('Jobfinder.urls')),
    path('admin/', admin.site.urls),
]

Others/jobFinder - Django/Jobfinder/urls.py
from django.urls import path

from . import views

app_name='polls'

urlpatterns =[

    path('', views.IndexViewHirer.as_view(), name='index'),
    path('<int:job_id>/', views.detail, name='detail')

]

Others/jobFinder - Django/Jobfinder/models.py
from django.db import models

# Create your models here.

class HirerAccounts(models.Model):
    fname = models.CharField(max_length=200)
    lname = models.CharField(max_length=200)
    phoneNum= models.CharField(max_length=200)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=200)

    def __str__(self):
        return self.email

class EmployeeAccounts(models.Model):
    fname = models.CharField(max_length=200)
    lname = models.CharField(max_length=200)
    phoneNum= models.CharField(max_length=200)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=200)

    def __str__(self):
        return self.email

class Hirer(models.Model):
    jobTitle = models.CharField(max_length=200)
    jobCategory = models.CharField(max_length=200)
    jobDescription = models.TextField()
    jobRequirements = models.TextField()
    salary = models.CharField(max_length=200)
    jobNature = models.CharField(max_length=200)
    jobExperience = models.TextField()
    location = models.CharField(max_length=200)
    companyName = models.CharField(max_length=200)
    companyEmail = models.EmailField(max_length=200)

    def __str__(self):
        return self.jobTitle    

class Employee(models.Model):
    fullname = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    letter = models.TextField()
    applicants = models.ForeignKey(Hirer, on_delete=models.CASCADE)

    def __str__(self):
        return self.fullname
  

Others/jobFinder - Django/Jobfinder/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic


from .models import Hirer, Employee

class IndexViewHirer(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_job_list'

    def get_queryset(self):
        return Hirer.objects.order_by('jobTitle')

def detail(request, job_id):

    student = get_object_or_404(Hirer, pk=job_id)
    return render (request, 'polls/detail.html',{
        'job':job,
    })
    return HttpResponseRedirect(reverse('polls:index'))

Others/jobFinder - Django/Jobfinder/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <title>Details of the Students</title>

    <style>
        .form-control{
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
            font-size: medium;
            color: black;
        }
        .form-group label{
            font-size: large;
        }
        thead{
            font-size: large;
        }
    </style>

</head>

<body>
    <nav class="navbar navbar-expand-sm bg-primary navbar-dark">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand"></a>
            </div>
        </div>
    </nav>

    <div class="row">
        <div class="container">

            <div class="col-md-12">
                <h2 style="text-align: center;">Student Details of {{ job.jobTitle  }}</h2><br />
            </div>

            <div class="col-md-6">
                <form>
                    <div class="form-group">
                        <label for="jobTitle">Job Title:</label>
                        <input type="text" class="form-control" value="{{ job.jobTitle }}" disabled>
                    </div>
                    <div class="form-group">
                        <label for="jobCategory">Job Category:</label>
                        <input type="text" class="form-control" value="{{ job.jobCategory }}" disabled>
                    </div>
                   
                </form>
            </div>

            <div class="col-md-6">
                <table class="table table-striped table-hover">
                    <thead class="thead-dark">
                        <tr>
                            <th>Job Title</th>
                            <th>Job Category</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% csrf_token %}
                            {% for employee in job.employee_set.all %}
                                <tr>
                                    <td>
                                        <h5>{{ employee.fullname }}</h5>
                                    </td>

                                    <td>
                                        <h5>{{ employee.email }}</h5>
                                    </td>
                                </tr>
                            {% endfor %}
                    </tbody>
                </table>
                <a href="{% url 'polls:index' %}"><button style="float: right;" class="btn btn-primary">Return to List</button></a>
            </div>

        </div>
    </div>
    
</body>
</html>

Others/jobFinder - Django/Jobfinder/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <title>List of Students</title>
</head>
<style>
    thead{
        font-size: x-large;
    }
    td{
        text-transform: capitalize;
    }
</style>

<body>
    <nav class="navbar navbar-expand-sm bg-primary navbar-dark">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" ></a>
            </div>
        </div>
    </nav>

    <div class="row">
        <div class="container"><br/>

            <div class="col-md-12">
                <h2 >Student Details Management</h2>
            </div>

            <div class="col-md-12"><br />
                <table class="table table-striped table-hover ">
                        <thead class="thead-dark">
                            <tr>
                                <th>Job Category</th>
                                <th>Student Details</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if latest_job_list %}
                                {% for job in latest_job_list %}
                                    <tr>
                                        <td>
                                            <h5>{{ job.jobTitle }}</h5>
                                        </td>
                                    
                                        <td>
                                            <a href="{% url 'polls:detail' job.id %}"><button class="btn btn-primary">See Details</button></a>
                                        </td>
                                    </tr> 
                                {% endfor %}      

                            {% else %}
                                            
                                <p>No polls are available.</p>

                            {% endif%}
                        </tbody>
                </table>
            </div>
        </div>
    </div>
    
    
</body>
</html>