Others/CSIPT101/CSIPT101/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('MidtermALVA/',include('MidtermALVA.urls')),
    path('admin/', admin.site.urls),
]

Others/CSIPT101/MidtermALVA/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    
    path('', views.IndexView.as_view(), name='index'),
    
    path('<int:student_id>/', views.detail, name='detail'),

]

Others/CSIPT101/MidtermALVA/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    studentNumber = models.CharField(max_length=200)
    fullName = models.CharField(max_length=200)
    course = models.CharField(max_length=200)
    year= models.CharField(max_length=200)

    def __str__(self):
       return self.studentNumber
    
         
class Grades(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    subjectCode = models.CharField(max_length=200)
    grade = models.IntegerField(default=0)

    def __str__(self):
       return self.subjectCode
   
       

Others/CSIPT101/MidtermALVA/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.template import loader

from .models import Student, Grades


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_student_list'

    def get_queryset(self):
        return Student.objects.order_by('fullName')

def detail(request, student_id):

    student = get_object_or_404(Student, pk=student_id)
    return render (request, 'polls/detail.html',{
        'student': student,  
    })
    return HttpResponseRedirect(reverse('polls:index'))
  
 

Others/CSIPT101/MidtermALVA/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
    <title>Details of the students</title>

    <style>
        .form-control{
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
            font-size: medium;
            color: black;
        }
        .form-group label{
            font-size: large;
        }
        thead{
            font-size: large;
        }
    </style>
</head>
<body>

    <nav class="navbar navbar-expand-sm bg-primary navbar-dark">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" ></a>
            </div>
        </div>
    </nav>

    <div class="row">
        <div class="container">
            
            <div class="col-md-12">
                <h2 style="text-align: center;">Student Details of {{ student.fullName  }}</h2><br />
            </div>

            <div class="col-md-6">
                
                <form>
                    <div class="form-group">
                        <label for="studentNumber">Student Number:</label>
                        <input type="text" class="form-control" value="{{ student.studentNumber  }}" disabled>
                    </div>
                    <div class="form-group">
                        <label for="fullName">Student Full Name:</label>
                        <input type="text" class="form-control" value="{{ student.fullName  }}" disabled>
                    </div>
                    <div class="form-group">
                        <label for="course">Student Course:</label>
                        <input type="text" class="form-control" value="{{ student.course  }}" disabled>
                    </div>
                    <div class="form-group">
                        <label for="course">Student Year:</label>
                        <input type="text" class="form-control" value="{{ student.year  }}" disabled>
                    </div>  
                </form>

                {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                {% endif %}

            </div>

            <div class="col-md-6">
                <table class="table table-striped table-hover ">
                    <thead class="thead-dark">
                        <tr>
                            <th>Student Subject Code</th>
                            <th>Student Grades</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% csrf_token %}
                            {% for grades in student.grades_set.all %}
                                <tr>
                                    <td>
                                        <h4>{{grades.subjectCode}}</h4>
                                    </td>
                                
                                    <td>
                                        <h4>{{ grades.grade }}</h4>
                                    </td>
                                </tr> 
                            {% endfor %}
                    </tbody>
                </table>
                <a href="{% url 'polls:index' %}"><button style="float: right;" class="btn btn-primary">Return to List</button></a>
            </div>
        </div>
    </div>
        
</body>
</html>

Others/CSIPT101/MidtermALVA/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <title>List of Students</title>
</head>
<style>
    thead{
        font-size: x-large;
    }
    td{
        text-transform: capitalize;
    }
</style>

<body>
    <nav class="navbar navbar-expand-sm bg-primary navbar-dark">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" ></a>
            </div>
        </div>
    </nav>

    <div class="row">
        <div class="container"><br/>

            <div class="col-md-12">
                <h2 >Student Details Management</h2>
            </div>

            <div class="col-md-12"><br />
                <table class="table table-striped table-hover ">
                        <thead class="thead-dark">
                            <tr>
                                <th>Student Name</th>
                                <th>Student Details</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if latest_student_list %}
                                {% for student in latest_student_list %}
                                    <tr>
                                        <td>
                                            <h5>{{ student.fullName }}</h5>
                                        </td>
                                    
                                        <td>
                                            <a href="{% url 'polls:detail' student.id %}"><button class="btn btn-primary">See Details</button></a>
                                        </td>
                                    </tr> 
                                {% endfor %}      

                            {% else %}
                                            
                                <p>No polls are available.</p>

                            {% endif%}
                        </tbody>
                </table>
            </div>
        </div>
    </div>
    
    
</body>
</html>